<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=robots content="noodp"><title>Exception handling in F# |</title><meta name=Description content="Functional-first approach to .NET exceptions"><meta property="og:title" content="Exception handling in F#"><meta property="og:description" content="Functional-first approach to .NET exceptions"><meta property="og:type" content="article"><meta property="og:url" content="https://autoforecastteam.github.io/posts/fsharp-errors/"><meta property="article:published_time" content="2021-02-09T11:03:32+01:00"><meta property="article:modified_time" content="2021-02-09T11:03:32+01:00"><meta name=twitter:card content="summary"><meta name=twitter:title content="Exception handling in F#"><meta name=twitter:description content="Functional-first approach to .NET exceptions"><meta name=application-name content="AutoForecast Team's blog"><meta name=apple-mobile-web-app-title content="AutoForecast Team's blog"><link rel="shortcut icon" type=image/x-icon href=/favicon.ico><link rel=icon type=image/png sizes=32x32 href=/favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=/favicon-16x16.png><link rel=apple-touch-icon sizes=180x180 href=/apple-touch-icon.png><link rel=manifest href=/site.webmanifest><link rel=canonical href=https://autoforecastteam.github.io/posts/fsharp-errors/><link rel=prev href=https://autoforecastteam.github.io/posts/adding-content/><link rel=stylesheet href=/lib/normalize/normalize.min.css><link rel=stylesheet href=/css/style.min.css><link rel=stylesheet href=/lib/fontawesome-free/all.min.css><link rel=stylesheet href=/lib/animate/animate.min.css><script type=application/ld+json>{"@context":"http://schema.org","@type":"BlogPosting","headline":"Exception handling in F#","inLanguage":"en","mainEntityOfPage":{"@type":"WebPage","@id":"https:\/\/autoforecastteam.github.io\/posts\/fsharp-errors\/"},"genre":"posts","wordCount":626,"url":"https:\/\/autoforecastteam.github.io\/posts\/fsharp-errors\/","datePublished":"2021-02-09T11:03:32+01:00","dateModified":"2021-02-09T11:03:32+01:00","publisher":{"@type":"Organization","name":"Author"},"author":{"@type":"Person","name":"Author"},"description":"Functional-first approach to .NET exceptions"}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/autoforecastteam.github.io\/"},{"@type":"ListItem","position":2,"name":"FSharp","item":"https://autoforecastteam.github.io/categories/fsharp/"},{"@type":"ListItem","position":3,"name":"Exception handling in F#"}]}</script></head><body data-header-desktop data-header-mobile><script>(window.localStorage&&localStorage.getItem('theme')?localStorage.getItem('theme')==='dark':(''==='auto'?window.matchMedia('(prefers-color-scheme: dark)').matches:''==='dark'))&&document.body.setAttribute('theme','dark');</script><div id=mask></div><div class=wrapper><header class=desktop id=header-desktop><div class=header-wrapper><div class=header-title><a href=/ title="AutoForecast Team's blog" class=header-logo>AutoForecast Team's blog</a></div><div class=menu><div class=menu-inner><a class=menu-item href=/posts/>Posts </a><a class=menu-item href=/tags/>Tags </a><a class=menu-item href=/categories/>Categories </a><span class="menu-item delimiter"></span><a href=javascript:void(0); class="menu-item theme-switch" title="Switch Theme"><i class="fas fa-adjust fa-fw"></i></a></div></div></div></header><header class=mobile id=header-mobile><div class=header-container><div class=header-wrapper><div class=header-title><a href=/ title="AutoForecast Team's blog" class=header-logo>AutoForecast Team's blog</a></div><div class=menu-toggle id=menu-toggle-mobile><span></span><span></span><span></span></div></div><div class=menu id=menu-mobile><a class=menu-item href=/posts/>Posts</a><a class=menu-item href=/tags/>Tags</a><a class=menu-item href=/categories/>Categories</a><a href=javascript:void(0); class="menu-item theme-switch" title="Switch Theme">
<i class="fas fa-adjust fa-fw"></i></a></div></div></header><main class=main><div class="container content-article theme-classic"><div class=toc id=toc-auto><div class=toc-title>Contents</div><div class=toc-content id=toc-content-auto></div></div><div class=header-post><div class=post-title><div class=post-all-meta><div class=breadcrumbs><a href=/>Home </a>/ <a href=/categories/fsharp/>FSharp </a>/ <a href=/>Exception handling in F#</a></div><h1 class="single-title animated flipInX">Exception handling in F#</h1><div class=post-meta><div class=post-meta-line><span class=post-category><a href=/categories/fsharp/><i class="far fa-folder fa-fw"></i>&nbsp;FSharp</a>
</span>&nbsp;&nbsp;&nbsp;&nbsp;<i class="far fa-calendar-alt fa-fw"></i>&nbsp;<time class=timeago datetime=2021-02-09>2021-02-09</time>&nbsp;&nbsp;&nbsp;&nbsp;<i class="fas fa-pencil-alt fa-fw"></i>&nbsp;626 words
&nbsp;&nbsp;&nbsp;&nbsp;<i class="far fa-clock fa-fw"></i>&nbsp;3 minutes</div></div></div></div></div><article class="single toc-start"><div class="content-block content-block-first content-block-position"><div class=post><div class="details toc" id=toc-static data-kept><div class="details-summary toc-title"><span>Contents</span>
<span><i class="details-icon fas fa-angle-right"></i></span></div><div class="details-content toc-content" id=toc-content-static><nav id=TableOfContents><ul><li><a href=#try-catch>Try-catch</a></li><li><a href=#problem-with-hofs-and-partial-application>Problem with HOFs and partial application</a></li><li><a href=#alternative-approach>Alternative approach</a></li><li><a href=#disclaimer>Disclaimer</a></li></ul></nav></div></div><h1 id=exception-handling-in-f>Exception Handling in F#</h1><h2 id=try-catch>Try-catch</h2><p>Simplest way to handle Exception is to use a try-with pattern. It is similar concept to a <a href=https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch target=_blank rel="noopener noreffer">try-catch pattern in C#</a>.
According to an <a href=https://docs.microsoft.com/pl-pl/dotnet/fsharp/language-reference/exception-handling/the-try-with-expression target=_blank rel="noopener noreffer">F# documentation</a> a structure of try-catch block is</p><div class=highlight><pre class=chroma><code class=language-fsharp data-lang=fsharp><span class=k>try</span>
    <span class=n>expression1</span>
<span class=k>with</span>
<span class=o>|</span> <span class=n>pattern1</span> <span class=o>-&gt;</span> <span class=n>expression2</span>
<span class=o>|</span> <span class=n>pattern2</span> <span class=o>-&gt;</span> <span class=n>expression3</span>
<span class=o>...</span>
</code></pre></div><p>The shortest way we can write it is to give one catch-all pattern for all exception.
Then we can even drop the pipe and match directly after <code>with</code> clause:</p><div class=highlight><pre class=chroma><code class=language-fsharp data-lang=fsharp><span class=k>let</span> <span class=nv>operationThatFails</span> <span class=bp>()</span> <span class=o>=</span> <span class=n>failwith</span> <span class=s>&#34;Error&#34;</span>
<span class=k>let</span> <span class=nv>x</span> <span class=o>=</span>
  <span class=k>try</span>
    <span class=n>operationThatFails</span> <span class=bp>()</span>
  <span class=k>with</span> <span class=n>e</span> <span class=o>-&gt;</span> <span class=n>sprintf</span> <span class=s>&#34;Caught exception %A&#34;</span> <span class=n>e</span>
</code></pre></div><p>In above case the exception is handled correctly. Variable x evaluates to <code>"Caught exception System.Exception: Error"</code> string.</p><h2 id=problem-with-hofs-and-partial-application>Problem with HOFs and partial application</h2><p>There is one problem that has caught me unexpectedly.</p><p>I was working on a function that did a lookup on CsvRow from <a href=http://fsprojects.github.io/FSharp.Data/ target=_blank rel="noopener noreffer">FSharp.Data</a> package.
The first version was:</p><div class=highlight><pre class=chroma><code class=language-fsharp data-lang=fsharp><span class=k>let</span> <span class=nv>tryGetValue</span> <span class=o>(</span><span class=n>row</span><span class=o>:</span> <span class=n>CsvRow</span><span class=o>)</span> <span class=o>(</span><span class=n>columnName</span><span class=o>:</span> <span class=kt>string</span><span class=o>)</span> <span class=o>=</span>
   <span class=k>try</span>
       <span class=n>row</span><span class=o>.[</span><span class=n>columnName</span><span class=o>]</span>
   <span class=k>with</span>
   <span class=o>|</span> <span class=o>:?</span> <span class=n>KeyNotFoundException</span> <span class=o>-&gt;</span> <span class=n>failwithf</span> <span class=s>&#34;Missing column: %s&#34;</span> <span class=n>columnName</span>
</code></pre></div><p>I used it to catch exceptions when there is a missing column name in CSV and then rethrow
with better message. Default exception message was too cryptic for my use case.</p><p>After couple of minutes I thought that it would be a good idea to refactor this into a
higher-order function that will be partially applied.</p><div class=highlight><pre class=chroma><code class=language-fsharp data-lang=fsharp><span class=k>let</span> <span class=nv>tryGetValue</span> <span class=o>(</span><span class=n>columnName</span><span class=o>:</span> <span class=kt>string</span><span class=o>)</span> <span class=o>=</span>
   <span class=k>try</span>
       <span class=k>fun</span> <span class=o>(</span><span class=n>x</span><span class=o>:</span> <span class=n>CsvRow</span><span class=o>)</span> <span class=o>-&gt;</span> <span class=n>x</span><span class=o>.[</span><span class=n>columnName</span><span class=o>]</span>
   <span class=k>with</span>
   <span class=o>|</span> <span class=o>:?</span> <span class=n>KeyNotFoundException</span> <span class=o>-&gt;</span> <span class=n>failwithf</span> <span class=s>&#34;Missing column: %s&#34;</span> <span class=n>columnName</span>
</code></pre></div><p>At first glance it looked OK. The only problem is, that this solution did not work.</p><p>In this case exceptions are caught only for the anonymous function creation part.
Application of my newly created function happens in another context, which may or may not have
its own exception handling.</p><p>Similar thing happens with partial application:</p><div class=highlight><pre class=chroma><code class=language-fsharp data-lang=fsharp><span class=k>let</span> <span class=nv>operationThatFails</span> <span class=o>(_:</span> <span class=kt>string</span><span class=o>)</span> <span class=o>(_:</span> <span class=kt>string</span><span class=o>)</span> <span class=o>:</span> <span class=kt>string</span> <span class=o>=</span> <span class=n>failwith</span> <span class=s>&#34;Error&#34;</span>

<span class=k>let</span> <span class=nv>x</span> <span class=o>=</span>
  <span class=k>try</span>
    <span class=n>operationThatFails</span> <span class=s>&#34;str1&#34;</span> <span class=s>&#34;str2&#34;</span>
  <span class=k>with</span>
  <span class=o>|</span> <span class=n>e</span> <span class=o>-&gt;</span> <span class=n>failwithf</span> <span class=s>&#34;Caught exception %A&#34;</span> <span class=n>e</span>

<span class=k>let</span> <span class=nv>partiallyApplied</span> <span class=o>:</span> <span class=o>(</span><span class=kt>string</span> <span class=o>-&gt;</span> <span class=kt>string</span><span class=o>)</span> <span class=o>=</span>
  <span class=k>try</span>
    <span class=n>operationThatFails</span> <span class=s>&#34;str1&#34;</span>
  <span class=k>with</span>
  <span class=o>|</span> <span class=n>e</span> <span class=o>-&gt;</span> <span class=n>failwithf</span> <span class=s>&#34;Caught exception %A&#34;</span> <span class=n>e</span>

<span class=k>let</span> <span class=nv>y</span> <span class=o>=</span> <span class=n>partiallyApplied</span> <span class=s>&#34;str2&#34;</span>
</code></pre></div><p>Variable x evaluates to string <code>"Caught exception [...]"</code>.</p><p>Evaluation of y fails with <code>System.Exception: Error</code></p><h2 id=alternative-approach>Alternative approach</h2><p>An interesting (and more functional) way to handle exceptions is to use an
<a href=https://github.com/fsprojects/FSharpPlus target=_blank rel="noopener noreffer">FSharpPlus</a> library.
There is a simple (but very helpful) function <code>protect</code> for <code>Result</code> type:</p><div class=highlight><pre class=chroma><code class=language-fsharp data-lang=fsharp><span class=k>let</span> <span class=nv>protect</span> <span class=o>(</span><span class=n>f</span><span class=o>:</span> <span class=k>&#39;</span><span class=n>T</span><span class=o>-&gt;</span><span class=k>&#39;</span><span class=n>U</span><span class=o>)</span> <span class=o>(</span><span class=n>x</span><span class=o>:</span> <span class=k>&#39;</span><span class=n>T</span><span class=o>)</span> <span class=o>:</span> <span class=n>Result</span><span class=o>&lt;</span><span class=k>&#39;</span><span class=n>U</span><span class=o>,</span><span class=kt>exn</span><span class=o>&gt;</span> <span class=o>=</span>
        <span class=k>try</span>
            <span class=n>Ok</span> <span class=o>(</span><span class=n>f</span> <span class=n>x</span><span class=o>)</span>
        <span class=k>with</span> <span class=n>e</span> <span class=o>-&gt;</span> <span class=n>Error</span> <span class=n>e</span>
</code></pre></div><p>Each time we deal with a function/method that throws exceptions we can wrap it
and apply in safe <code>Result</code> context:</p><div class=highlight><pre class=chroma><code class=language-fsharp data-lang=fsharp><span class=k>let</span> <span class=nv>iWillThrow</span> <span class=bp>()</span> <span class=o>:</span> <span class=kt>string</span> <span class=o>=</span> <span class=n>failwith</span> <span class=s>&#34;Error&#34;</span>

<span class=nn>Result</span><span class=p>.</span><span class=n>protect</span> <span class=n>iWillThrow</span>  <span class=c1>// Wrap
</span><span class=c1></span><span class=o>|&gt;</span> <span class=k>fun</span> <span class=n>x</span> <span class=o>-&gt;</span> <span class=n>x</span> <span class=bp>()</span>           <span class=c1>// Apply
</span><span class=c1></span><span class=o>|&gt;</span> <span class=k>function</span>                <span class=c1>// Handle Result
</span><span class=c1></span>   <span class=o>|</span> <span class=n>Ok</span> <span class=n>v</span>    <span class=o>-&gt;</span> <span class=n>sprintf</span> <span class=s>&#34;Value was: %s&#34;</span> <span class=n>v</span>
   <span class=o>|</span> <span class=n>Error</span> <span class=n>e</span> <span class=o>-&gt;</span> <span class=n>sprintf</span> <span class=s>&#34;There was an error: %A&#34;</span> <span class=n>e</span>
</code></pre></div><p>If we don&rsquo;t care about thrown exception we can just use <code>Option.protect</code>, which will
return <code>None</code> for all failed cases.</p><p>There is a caveat though, that <code>protect</code> accepts only functions that take a single parameter.
However, this constraint may actually be benefitial, because it saves us from making the same mistake
that I did.</p><p>Partially applied <code>tryGetValue</code> function would then be:</p><div class=highlight><pre class=chroma><code class=language-fsharp data-lang=fsharp><span class=k>let</span> <span class=nv>tryGetValue</span> <span class=o>(</span><span class=n>columnName</span><span class=o>:</span> <span class=kt>string</span><span class=o>)</span> <span class=o>=</span>
   <span class=k>fun</span> <span class=o>(</span><span class=n>x</span><span class=o>:</span> <span class=n>CsvRow</span><span class=o>)</span> <span class=o>-&gt;</span> <span class=n>x</span><span class=o>.[</span><span class=n>columnName</span><span class=o>]</span>
   <span class=o>|&gt;</span> <span class=nn>Option</span><span class=p>.</span><span class=n>protect</span>
   <span class=o>|&gt;&gt;</span> <span class=nn>Option</span><span class=p>.</span><span class=n>defaultWith</span> <span class=o>(</span><span class=k>fun</span> <span class=bp>()</span> <span class=o>-&gt;</span> <span class=n>failwithf</span> <span class=s>&#34;Missing column: %s&#34;</span> <span class=n>columnName</span><span class=o>)</span>
</code></pre></div><p>where <code>|>></code> is just an FSharpPlus operator for <code>Option.map</code> function.</p><h2 id=disclaimer>Disclaimer</h2><p>In all examples above, <code>tryGetValue</code> remains a partial function. It will fail for all <code>columnName</code> values
that are not contained in CsvRow. It is written that way, because in my example I treat missing column name
as an unrecoverable error. I apply <a href=https://en.wikipedia.org/wiki/Fail-fast target=_blank rel="noopener noreffer">Fail-fast</a> principle,
which means that I want to stop further processing immediately.</p></div><div class=post><div class=post-info-share><span></span></div><div class=post-footer id=post-footer><div class=post-navigation><div class="post-nav-box nav-box-prev"><a class=nav-box href=/posts/adding-content/><span class=nav-icon><svg aria-hidden="true" data-prefix="fas" data-icon="chevron-circle-left" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentcolor" d="M256 504C119 504 8 393 8 256S119 8 256 8s248 111 248 248-111 248-248 248zM142.1 273l135.5 135.5c9.4 9.4 24.6 9.4 33.9.0l17-17c9.4-9.4 9.4-24.6.0-33.9L226.9 256l101.6-101.6c9.4-9.4 9.4-24.6.0-33.9l-17-17c-9.4-9.4-24.6-9.4-33.9.0L142.1 239c-9.4 9.4-9.4 24.6.0 34z"/></svg></span><div style=text-align:right;padding-left:10px><div class=nav-text-h>Next article</div><span class=nav-text>Adding content</span></div></a></div></div></div></div></div><div id=toc-final></div></article></div></main></div><div id=fixed-buttons><a href=# id=back-to-top class=fixed-button title="Back to Top"><i class="fas fa-arrow-up fa-fw"></i></a><a href=# id=view-comments class=fixed-button title="View Comments"><i class="fas fa-comment fa-fw"></i></a></div><script src=/lib/smooth-scroll/smooth-scroll.min.js></script><script src=/lib/lazysizes/lazysizes.min.js></script><script src=/lib/clipboard/clipboard.min.js></script><script>window.config={"code":{"copyTitle":"Copy to clipboard","maxShownLines":10}};</script><script src=/js/theme.min.js></script><script src=/js/jquery-3.5.1.min.js></script></body></html>